### ISSUE TITLE
yo 创建的项目 npm install 报错node prebuild

### ISSUE THREAD

**Issue by CGerAJ** [weixin/tmt-workflow#107]
![qq 20170503205033](https://cloud.githubusercontent.com/assets/20548301/25661201/363fd1e4-3042-11e7-912b-183dc980b2f2.png)
Error: Command failed: node-gyp rebuild
gyp ERR! clean error
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'E:\phpStudy\WWW\locales\node_modules\_node-lwip@0.1.3@node-lwip\build\Release\lwip_decoder.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\phpStudy\WWW\locales\node_modules\_node-lwip@0.1.3@node-lwip
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
× Install fail! Error: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c node prebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c node prebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:65:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by GarethChu** [comment]
跟你类似的错误，折腾了一下午都没装好。
貌似都没有维护了

**Comment by hzlzh** [comment]
两位，尝试一下直接用 cnpm 安装呢

* 全局安装 Gulp 4，执行：cnpm install gulpjs/gulp#4.0 -g
* 点击下载 tmt-workflow，进入根目录执行： cnpm install

**Comment by huysh3** [comment]
在node@6.10.2下碰到同样问题，
yo和直接下载都有问题，
切换到node@5.3.0就好了

**Comment by CGerAJ** [comment]
cnpm 装的模块和npm装的模块会存在冲突 要不用cnpm 要不用cpm  目前都没用这个工作流了

**Comment by hzlzh** [comment]
@CGerAJ 会有这样的问题，如果网络环境 OK，优先用官方的 npm 比较好。
