### ISSUE TITLE
npm install exception occurred

### ISSUE THREAD

**Issue by willyang** [weixin/tmt-workflow#60]
module.js:328
    throw err;
    ^

Error: Cannot find module '../build/Release/lwip_image'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by willyang** [comment]
modify package.json dependencies the "gulp-tmtsprite" 
modified package.json  the "gulp-tmtsprite"  depends on version "^0.0.22"

**Comment by littledu** [comment]
^0.0.21

安装的时候，会安装到 0.0.22 的
