### ISSUE TITLE
build_dev报错

### ISSUE THREAD

**Issue by Pumpe** [weixin/tmt-workflow#84]
$ gulp build_dev
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'D:\wwwroot\topic\lucky\node_modules\.3.13.1@node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (D:\wwwroot\topic\lucky\node_modules\.3.13.1@node-sass\lib\extensions.js:121:13)
    at foundBinariesList (D:\wwwroot\topic\lucky\node_modules\.3.13.1@node-sass\lib\errors.js:20:15)
    at foundBinaries (D:\wwwroot\topic\lucky\node_modules\.3.13.1@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (D:\wwwroot\topic\lucky\node_modules\.3.13.1@node-sass\lib\errors.js:45:5)
    at module.exports (D:\wwwroot\topic\lucky\node_modules\.3.13.1@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (D:\wwwroot\topic\lucky\node_modules\.3.13.1@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by littledu** [comment]
重新执行 cnpm install gulp-sass

**Comment by Pumpe** [comment]
嗯，cache clean之后去掉sass的依赖项就可以了，重新安装就搞定了，很奇怪的是在mac下就没问题，在windows下就会一直报错

**Comment by littledu** [comment]
因为 windows 下编译需要依赖 VS 和 python2.7，默认的windows都是没有这两个东西的，所以基本都编译不过，而 mac 的编译环境 xcode 和 phthon2.7 都是自带的，所以没有问题。
