### ISSUE TITLE
build_dev问题 no such a file or directory

### ISSUE THREAD

**Issue by CodeMagic6** [weixin/tmt-workflow#94]
`Error: ENOENT: no such file or directory, scandir 'C:\Users\wangkai\WebstormProjects\H5-Static\ysjs\201703\dev\html'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at listdir (C:\Users\wangkai\WebstormProjects\H5-Static\_tasks\plugins\TmTIndex.js:45:20)
    at module.exports (C:\Users\wangkai\WebstormProjects\H5-Static\_tasks\plugins\TmTIndex.js:32:21)
    at C:\Users\wangkai\WebstormProjects\H5-Static\_tasks\lib\util.js:29:38
    at Array.every (native)
    at Object.tmt_util.loadPlugin (C:\Users\wangkai\WebstormProjects\H5-Static\_tasks\lib\util.js:21:21)
    at loadPlugin (C:\Users\wangkai\WebstormProjects\H5-Static\_tasks\TaskBuildDev.js:278:14)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
[10:46:02] 'build_dev' errored after 281 ms
`
请问每次build_dev都报这个错误是什么原因呢，创建了html文件夹，或者文件都没用呢

**Comment by hzlzh** [comment]
尝试一下重新安装依赖：https://npm.taobao.org/
