### ISSUE TITLE
npm install 报错！！！无法正常下载 node:6.10版的

### ISSUE THREAD

**Issue by ipengyo** [weixin/tmt-workflow#99]
```

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node prebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node prebuild" error, exit code 1
    at ChildProcess.proc.on.code (/Users/ipengyo/.nvm/versions/node/v6.10.2/lib/node_modules/cnpm/node_modules/runscript/index.js:65:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 2.29.1
npminstall args: /Users/ipengyo/.nvm/versions/node/v6.10.2/bin/node /Users/ipengyo/.nvm/versions/node/v6.10.2/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/ipengyo/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org
```

**Comment by ipengyo** [comment]
![image](https://cloud.githubusercontent.com/assets/9323722/24837932/86bb9d26-1d71-11e7-9fa4-d2be746b909b.png)

**Comment by littledu** [comment]
你这个保存没截全吧，看不出是哪个模块没安装成功。410491325 ，可以加我QQ给你解决

**Comment by ipengyo** [comment]
谢谢大神回复，我已经加你qq拉！！

**Comment by littledu** [comment]
可能是你的xcode问题，
需要同意新的协议，试下执行下面命令后再安装
sudo xcodebuild -license accept

**Comment by ipengyo** [comment]
➜  tmt cnpm install
⠋ [gulp@git://github.com/gulpjs/gulp#4.0] install gulp from git git://github.com/gulpjs/gulp.git#4.0, may be very slow, please keep patience
✔ Installed 34 packages
✔ Linked 744 latest versions
  ✔ optipng pre-build test passed successfully
  ✔ jpegtran pre-build test passed successfully
  ✔ gifsicle pre-build test passed successfully
  ✔ cwebp pre-build test passed successfully
  ✔ pngquant pre-build test passed successfully
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o

In file included from ../src/decoder/init.cpp
:1:
In file included from ../src/decoder/decoder.h:13:
In file included from ../../._nan@2.0.9@nan/nan.h:182:
../../._nan@2.0.9@nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]

  return array->CloneElementAt(GetCurrentContext(), index);

                ^

/Users/ipengyo/.node-gyp/6.10.2/include/node/v8.h:
3032:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^

In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13
:
In file included from ../../._nan@2.0.9@nan/nan.h:188:
In file included from ../../._nan@2.0.9@nan/nan_new.h:189:
../../._nan@2.0.9@nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/ipengyo/.node-gyp/6.10.2/include/node/v8.h:4008:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^

In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../._nan@2.0.9@nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'

      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^

../../._nan@2.0.9@nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'

      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^

../../._nan@2.0.9@nan/nan.h:601:
20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^

../../._nan@2.0.9@nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'

      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^

../../._nan@2.0.9@nan/nan.h:
1927:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/ipengyo/.node-gyp/6.10.2/include/node/v8.h:2751:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^

3 warnings and 4 errors generated.

make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1

gyp

ERR! build error


gyp
 ERR! stack Error: `make` failed with exit code: 2
gyp
ERR! stack     at ChildProcess.onExit (/Users/ipengyo/.nvm/versions/node/v6.10.2/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:285:23)

gyp ERR!
 stack     at emitTwo (events.js:106:13)

gyp ERR!
 stack
     at ChildProcess.emit (events.js:191:7)

gyp ERR!
 stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp
 ERR! System
 Darwin 16.5.0

gyp ERR!
command
 "/Users/ipengyo/.nvm/versions/node/v6.10.2/bin/node" "/Users/ipengyo/.nvm/versions/node/v6.10.2/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"

gyp
ERR!
cwd /Users/ipengyo/workspace/study/tmt/node_modules/._node-lwip@0.1.3@node-lwip

gyp
 ERR! node -v v6.10.2

gyp
ERR! node-gyp -v
 v3.6.0

gyp
ERR! not ok


child process exited with code 1
/Users/ipengyo/workspace/study/tmt/node_modules/._node-lwip@0.1.3@node-lwip/prebuild.js:123
        if (err) throw err;
                 ^

Error: Command failed: node-gyp rebuild
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
In file included from ../../._nan@2.0.9@nan/nan.h:182:
../../._nan@2.0.9@nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/ipengyo/.node-gyp/6.10.2/include/node/v8.h:3032:36: note: 'CloneElementAt' has been explicitly marked deprecated here
                MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                   ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
In file included from ../../._nan@2.0.9@nan/nan.h:188:
In file included from ../../._nan@2.0.9@nan/nan_new.h:189:
../../._nan@2.0.9@nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/ipengyo/.node-gyp/6.10.2/include/node/v8.h:4008:56: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../._nan@2.0.9@nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../._nan@2.0.9@nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../._nan@2.0.9@nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../._nan@2.0.9@nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../._nan@2.0.9@nan/nan.h:1927:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/ipengyo/.node-gyp/6.10.2/include/node/v8.h:2751:22: note: 'SetAccessor' has been explicitly marked deprecated here
                bool SetAccessor(Local<Name> name,
                     ^
3 warnings and 4 errors generated.
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ipengyo/.nvm/versions/node/v6.10.2/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/ipengyo/.nvm/versions/node/v6.10.2/bin/node" "/Users/ipengyo/.nvm/versions/node/v6.10.2/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ipengyo/workspace/study/tmt/node_modules/._node-lwip@0.1.3@node-lwip
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node prebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node prebuild" error, exit code 1
    at ChildProcess.proc.on.code (/Users/ipengyo/.nvm/versions/node/v6.10.2/lib/node_modules/cnpm/node_modules/runscript/index.js:65:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 2.29.1
npminstall args: /Users/ipengyo/.nvm/versions/node/v6.10.2/bin/node /Users/ipengyo/.nvm/versions/node/v6.10.2/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/ipengyo/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org

**Comment by littledu** [comment]
加我qq吧，我打个包给你

**Comment by ipengyo** [comment]
找到问题所在了，谢谢大神。

原因： 我是使用yo生成的代码，里面的一个依赖 gulp-tmtsprite 的依赖是 0.20的，而最新的已经来到了0.22

**Comment by yucccc** [comment]
遇到同样的问题 依赖是0.22  cnpm install 报错 
```
3 warnings and 4 errors generated.
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/yucccc/.nvm/versions/node/v8.2.1/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/yucccc/.nvm/versions/node/v8.2.1/bin/node" "/Users/yucccc/.nvm/versions/node/v8.2.1/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yucccc/test/myflow-three/node_modules/_node-lwip@0.1.3@node-lwip
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node prebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node prebuild" error, exit code 1
    at ChildProcess.proc.on.code (/Users/yucccc/.nvm/versions/node/v8.2.1/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by hzlzh** [comment]
@yucccc  node 版本号过高了，试试用 v 5.10.0，可以用 nvm 或者 [n](https://github.com/tj/n) 来切换
